**Задание 1**
Печатные газеты использовали свой формат дат для каждого выпуска. Для каждой газеты из списка напишите формат указанной даты для перевода в объект datetime:
The Moscow Times - Wednesday, October 2, 2002
The Guardian - Friday, 11.10.13
Daily News - Thursday, 18 August 1977

In [4]:
from datetime import datetime,timedelta
# справочник форматов дат
date_formats = {
    'Monday, January 01, 2022' : '%A, %B %d, %Y',
    'Monday, 01.12.22' : '%A, %d.%m.%y',
    'Monday, 01 January 2022' : '%A, %d %B %Y',
    'YYYY.MM.DD' : '%Y.%m.%d',
    'YYYY-MM-DD' : '%Y-%m-%d',
}

def check_date(date, format):
    '''
    Return True if date and format are a valid combination
    '''
    try:
        datetime.strptime(date, format)
        return True
    except:
        return False

def seek_dateformat(date):
    '''
    Return available output python date format
    '''
    # есть ли формат, соответствующий date
    for k, df in date_formats.items():
        if check_date(date, df):
            return df
    else:
        # print(f'Unknown date_format for {date}.') 
        return '%Y.%m.%d'

def date_format(date, cur_format = None):
    ''' 
    Convert date to cur_format ('%Y.%m.%d if None)
    '''
    if cur_format is None:
        if check_date(date, seek_dateformat(date)):
            return datetime.strftime(datetime.strptime(date, seek_dateformat(date)), '%Y.%m.%d')
    else:
        if check_date(date, seek_dateformat(date)):
                if cur_format in date_formats:
                    return datetime.strftime(datetime.strptime(date, seek_dateformat(date)), date_formats[cur_format])
                else:
                    print(f'Format {cur_format} is not in date_format list or not valid.')   
        else:
            # print(f'Unknown date_format for {date}.') 
            return 
# все строки прeобразуются в питоновский формат даты, затем происходит вывод в output формат

In [5]:
inp ='The Moscow Times - Wednesday, October 2, 2002 - The Guardian - Friday, 11.10.13 - Daily News - Thursday, 18 August 1977'
# формируем список из входной строки
list_ = inp.strip().split('-')
print(f'List to convert: {list_}\n')
result = {}
paper = list_[0].strip() # название первой газеты
result.setdefault(paper) 

for i, l in enumerate(list_):


    item = l.strip()
  
    if i % 2 != 0:  #  если нечетное число
        # можно указать любой выходной формат, по умолчанию 'YYYY.MM.DD'
        result[paper]= date_format(item)  
        # result[paper]= date_format(item, 'Monday, 01.12.22')   
    else:
      result.setdefault(item)
      paper = item

result

List to convert: ['The Moscow Times ', ' Wednesday, October 2, 2002 ', ' The Guardian ', ' Friday, 11.10.13 ', ' Daily News ', ' Thursday, 18 August 1977']

{'The Moscow Times': '2002.10.02',
 'The Guardian': '2013.10.11',
 'Daily News': '1977.08.18'}

**Задание 2**

Дан поток дат в формате YYYY-MM-DD, в которых встречаются некорректные значения:
stream = [‘2018-04-02’, ‘2018-02-29’, ‘2018-19-02’]

Напишите функцию, которая проверяет эти даты на корректность. Т. е. для каждой даты возвращает True (дата корректна) или False (некорректная дата).

In [6]:
stream = ['2018-04-02', '2018-02-29', '2018-19-02']

In [7]:
[check_date(s, seek_dateformat(s)) for s in stream]

[True, False, False]

**Задание 3**

Напишите функцию date_range, которая возвращает список дат за период от start_date до end_date. Даты должны вводиться в формате YYYY-MM-DD. В случае неверного формата или при start_date > end_date должен возвращаться пустой список.

In [8]:
def check_date_input(date, date_format):
    if check_date(date, date_format):
        return True
    else:
        return False

def  date_range(start_date, end_date):
    if   start_date > end_date:
        return list()
    else:
        
        return [datetime.strftime(start_date + timedelta(days=d), '%Y-%m-%d')
                                 for d in range((end_date - start_date).days+1)]

def date_input(str, date_format):
    while True:
        d = input(f'Enter {str} ({date_format}):')
        try:
            if check_date_input(d, date_formats[date_format]):
                return d
        except:
            print(f'Unknown date_format for {d, date_format}.') 
            return

In [9]:
date_format = 'YYYY-MM-DD' # задаем формат вывода по умолчанию  'YYYY-MM-DD'
start_date = datetime.strptime(date_input('Start date', date_format), date_formats[date_format]) 
end_date = datetime.strptime(date_input('End date', date_format), date_formats[date_format]) 
date_range(start_date, end_date)#, date_format)

Enter Start date (YYYY-MM-DD):2022.01.05
Enter Start date (YYYY-MM-DD):2022-01-05
Enter End date (YYYY-MM-DD):2022-02-05

['2022-01-05',
 '2022-01-06',
 '2022-01-07',
 '2022-01-08',
 '2022-01-09',
 '2022-01-10',
 '2022-01-11',
 '2022-01-12',
 '2022-01-13',
 '2022-01-14',
 '2022-01-15',
 '2022-01-16',
 '2022-01-17',
 '2022-01-18',
 '2022-01-19',
 '2022-01-20',
 '2022-01-21',
 '2022-01-22',
 '2022-01-23',
 '2022-01-24',
 '2022-01-25',
 '2022-01-26',
 '2022-01-27',
 '2022-01-28',
 '2022-01-29',
 '2022-01-30',
 '2022-01-31',
 '2022-02-01',
 '2022-02-02',
 '2022-02-03',
 '2022-02-04',
 '2022-02-05']

**Задание 4 (необязательное)**
Ваш коллега прислал код функции:

DEFAULT_USER_COUNT = 3

def delete_and_return_last_user(region, default_list=[‘A100’, ‘A101’, ‘A102’]):
""“
Удаляет из списка default_list последнего пользователя
и возвращает ID нового последнего пользователя.
”""
element_to_delete = default_list[-1]
default_list.remove(element_to_delete)

1
return default_list[DEFAULT_USER_COUNT-2]
При однократном вызове этой функции все работает корректно:
delete_and_return_last_user(1)
‘A101’

Однако, при повторном вызове получается ошибка IndexError: list index out of range.

Задание:

Что значит ошибка list index out of range?
Почему при первом запуске функция работает корректно, а при втором - нет?

In [10]:
DEFAULT_USER_COUNT = 3

def delete_and_return_last_user(region, default_list=['A100', 'A101', 'A102']):
    """
    Удаляет из списка default_list последнего пользователя
    и возвращает ID нового последнего пользователя.
    """
    element_to_delete = default_list[-1]
    print(f'default_list id:{id(default_list)}, element_to_delete id: {id(element_to_delete)}')

    default_list.remove(element_to_delete)
    return default_list[DEFAULT_USER_COUNT-2]

In [11]:
delete_and_return_last_user(1)

default_list id:140642524718096, element_to_delete id: 140642524620272

'A101'

In [12]:
delete_and_return_last_user(1)

default_list id:140642524718096, element_to_delete id: 140642632349808

IndexError: ignored

1. 'list index out of range' - Значит, что индекс, по которому идет обращение к списку default_list выходит за диапазон возможных значений.

2. При первом запуске функции из списка удаляется 1 элемент, потом идет обращение к индексу #1, т.е. ко  2-му элементу, т.е. "А101".

    При повторном вызове функции обращение в памяти к списку происходит по одному и тому же id, поэтому список не инициализируется вновь, а помнит своё последнее состояние. 

    Удаляется второй элемент и в списке остается только 1 элемент, а обращение идет ко второму (по индексу 1), поэтому возникает ошибка.